### ISSUE TITLE
How to add icons

### ISSUE THREAD

**Issue by davidszerman** [chhoumann/Templater_Templates#2]
Hello, 

I love your script ; how do you add/find other symbols in the first character of the choice list please ?

Thanks

**Comment by chhoumann** [comment]
Hey! Thank you.

I'm on Windows, so I can press `WIN+.` to find emojis. I do not know if there is a similar shortcut on other platforms.

However, I know that many Obsidian users use the "Emoji Toolbar" plugin. It's in the Community Plugin store, so you can just search for it and install it.

Hope this helps.
